Hooks: skip checks of folders
Although find is set to match on files, it also matches on pruned folders and so is passing those to the formatting checks.

diff --git a/hooks/blank-line-at-end-of-file-check b/hooks/blank-line-at-end-of-file-check
--- a/hooks/blank-line-at-end-of-file-check
+++ b/hooks/blank-line-at-end-of-file-check
@@ -9,16 +9,19 @@ git stash -q --keep-index
 exitStatus=0
 
 while read -r filename; do
-  # Check if the file is tracked by git
-  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
-    # Don't check untracked files
-    continue
-  fi
+  # Check if it's a file (find matches on pruned folders)
+  if [[ -f "$filename" ]]; then
+    # Check if the file is tracked by git
+    if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
+      # Don't check untracked files
+      continue
+    fi
 
-  if tail -1 "$filename" | grep --binary-files=without-match --regexp="^$"; then
-    echo "ERROR: Blank line found at end of $filename"
-    # Make the hook fail
-    exitStatus=1
+    if tail -1 "$filename" | grep --binary-files=without-match --regexp="^$"; then
+      echo "ERROR: Blank line found at end of $filename"
+      # Make the hook fail
+      exitStatus=1
+    fi
   fi
 done <<<"$(find . -path './.git' -prune -or -type f)"
 
diff --git a/hooks/non-unix-eol-check b/hooks/non-unix-eol-check
--- a/hooks/non-unix-eol-check
+++ b/hooks/non-unix-eol-check
@@ -9,16 +9,19 @@ git stash -q --keep-index
 exitStatus=0
 
 while read -r filename; do
-  # Check if the file is tracked by git
-  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
-    # Don't check untracked files
-    continue
-  fi
+  # Check if it's a file (find matches on pruned folders)
+  if [[ -f "$filename" ]]; then
+    # Check if the file is tracked by git
+    if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
+      # Don't check untracked files
+      continue
+    fi
 
-  if grep --files-with-matches --binary-files=without-match --regexp=$'\r$' "$filename"; then
-    echo "ERROR: Non-Unix EOL detected in $filename"
-    # Make the hook fail
-    exitStatus=1
+    if grep --files-with-matches --binary-files=without-match --regexp=$'\r$' "$filename"; then
+      echo "ERROR: Non-Unix EOL detected in $filename"
+      # Make the hook fail
+      exitStatus=1
+    fi
   fi
 done <<<"$(find . -path './.git' -prune -or -type f)"
 
diff --git a/hooks/true-tabs-check b/hooks/true-tabs-check
--- a/hooks/true-tabs-check
+++ b/hooks/true-tabs-check
@@ -9,16 +9,19 @@ git stash -q --keep-index
 exitStatus=0
 
 while read -r filename; do
-  # Check if the file is tracked by git
-  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
-    # don't check untracked files
-    continue
-  fi
+  # Check if it's a file (find matches on pruned folders)
+  if [[ -f "$filename" ]]; then
+    # Check if the file is tracked by git
+    if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
+      # don't check untracked files
+      continue
+    fi
 
-  if grep --with-filename --line-number --binary-files=without-match --regexp=$'\t' "$filename"; then
-    echo "ERROR: True tab found in $filename"
-    # Make the hook fail
-    exitStatus=1
+    if grep --with-filename --line-number --binary-files=without-match --regexp=$'\t' "$filename"; then
+      echo "ERROR: True tab found in $filename"
+      # Make the hook fail
+      exitStatus=1
+    fi
   fi
 done <<<"$(find . -path './.git' -prune -or -type f)"
 
